### ISSUE TITLE
Separation of Authorization and Resource Storage

### ISSUE THREAD

**Issue by mdwheele** [dingo/oauth2-server#5]
I'm working on an auth. server implementation at the moment and my environment has requirements for a central auth server separated from many service providers (resource servers).  

It seems that this package is built from the perspective of having a united auth/resource server sharing a database.  I can work around this by implementing storage interfaces for validating tokens (and more), but I notice that your resource server implementation also deletes tokens when they are expired.  I've understood token management to be the responsibility of the authorization server (expiration, validation, returning identity + scopes to resources, etc)

``` php
if ($this->tokenHasExpired($token)) {
    $this->storage('token')->delete($token->getToken());

    throw new InvalidTokenException('expired_token', 'Access token has expired.', 401);
}
```

My question... with all this unnecessary text (brevity isn't my thing) is... are you open to contributions to open the package up to this type of use-case?  I'm a fan of your API package and would love to take advantage of any synergy between that package and this server implementation where possible.  

If so, do you have any initial thoughts towards my constraints and how you might envision bringing those into the package?  This package (overall) reduces the amount of custom code I'd have to write, so I'm willing to contribute that extra time here.

**Comment by mdwheele** [comment]
I'm reading http://tools.ietf.org/html/rfc6749#section-7 for reference:

> The client accesses protected resources by presenting the access
>    token to the resource server.  The resource server MUST validate the
>    access token and ensure that it has not expired and that its scope
>    covers the requested resource.  The methods used by the resource
>    server to validate the access token (as well as any error responses)
>    are beyond the scope of this specification but generally involve an
>    interaction or coordination between the resource server and the
>    authorization server.

In this case, I would expect it to simply check expiry and throw an exception; not going through the deletion of the token.  If I were to use this right now, I could implement a storage interface that made calls back to the authorization server, but would not want to open up endpoints for deleting tokens and more.  For this particular issue, my implementation would make an api call to a "verify token, get id/scopes" endpoint on the authorization server when `$token = $this->storage('token')->getWithScopes($token)` was called.  I could use this call to clean up on the authorization server side if the token was actually old (I currently have a worker cleaning up things like this).  With the current API, I would probably just stub out the delete method altogether and that IS an option.  

This is the first thing I noticed when browsing, so I'm not sure how much more of the package I would have to treat this way.  Perhaps not much more.

**Comment by jasonlewis** [comment]
Hm, so how would you recommend expired access tokens be dealt with? If the resource server doesn't delete them there's no way for the authorization server to know which tokens have expired. Plus you'd still need to manually invoke some kind of call to delete the expired tokens.

And the resource server is responsible for validating access tokens. So how would we go about validating tokens for a resource server that doesn't share the same database as the authorization server?

I'm definitely open to contributions for this kind of thing.

**Comment by mdwheele** [comment]
Yeah, I'm trying to reason around this as well.  Most implementations I've seen don't have reason for separation at all.  Here's what I've got so far:

Basically, the whole interaction starts with a client providing a bearer/access token to our resource server.  The resource server knows nothing about this token other than it's a string (in an "unpacked token implementation".. I will explain packed/unpacked later).  So, the resource server takes this string it knows nothing about and asks the authorization server to verify it.  You'll end up with a `/verify/{token}` (or something) endpoint on the authorization server.  For this example, we'll just imagine you pass the token in the URL.. this is a bad idea, but easier to talk around.

The resource server makes the request for `verify/389h9ijf9832j98fj239f` and is given a json response that represents data about the token which may include the client_id, user_id, user_type, expiration information, and any scopes attached.  The resource server MUST still verify the token has expired to handle cases where a request is made right before a token expires.  The resource server does not cache tokens in this implementation (it shouldn't ever store a registry of token -> user_id.  It only needs the user_id to be able to provide protected resources for that user.

Now, in the case that the token is expired... when the resource server asks the authorization server to verify the token it has, the authorization server MUST check whether or not the token has expired.  If it has, the authorization server should return some suitable response as such and then could delete the token at that point.

In addition, background workers running on the authorization server could run garbage collection tasks.  Removing expired tokens could be one of those tasks (although this has an impact on refresh token processing, so I'd need to think on that some more).

Finally, I try to think about who "owns" what.  The authorization server is responsible for deciding whether or not a client application is authorized to access a given protected resource.  Therefore, at least in my mind, the authorization server owns responsibility for access tokens.  This becomes very important when considering that **my** authorization server is downstream from an external identity provider (IdP).  When a user account is compromised in my environment, I have to be able to immediately revoke all access tokens granted to client applications on that user's behalf.  This is done at the authorization server point rather than at EACH resource server (which are out of my control).  

Just to be super-clear!  I'm still figuring this out myself, so don't take anything I say as golden, but this is what makes sense to me at the moment, given my environmental constraints.  It's something that could be brought into an existing package I'm sure, but it may not be worth it if the majority use-case isn't my own.  All that said, I **do** know that this is a use-case where there is not a lot of documented hand-holding, haha.  So take that for what it's worth.

Perhaps you could ping Twitter-verse and see if there's interest?  You have a bigger follower base than I'll ever have! :smile:

**Comment by mdwheele** [comment]
**"Packed vs Unpacked" Access Tokens**

This is documented briefly in the spec at http://tools.ietf.org/html/rfc6749#section-7.1.  Basically, what it boils down to is that "packed" tokens can be used to optimize the case I've described above whereby a resource server must ALWAYS ask the authorization server to verify tokens and return data about them.  

To reduce latency impact, the tokens would be "packed" with identity information (possibly the other data above, with consideration) and the resource server would be able to extract this without an interaction with the authorization server.  This has critical impact on the authorization server's ability to invalidate tokens.  Imagine a user viewing a web front-end to an authorization server whereby they can see all client applications that have tokens on their behalf.  The user could revoke tokens at the authorization server level while a client still maintains a packed token that a resource server would ASSUME is still valid until the expiration.  There would not be risk of client forging tokens because the packed token would not be decipherable/signable by a client.  Only the auth and resource servers would know how to extract identity from the token.  It's opaque to the client application.

**Comment by mdwheele** [comment]
I'll take a look at this again when I get into work.  It's 3:44am in the States!

**Comment by jasonlewis** [comment]
Okay I think I can see where you're coming from. And I can see why you'd be needing to do it. As for how to do it. I'm not too sure at the moment.

For now (`0.2-dev`) I've removed the deletion of access tokens if they have expired so only an exception is thrown.

Will have to look into how to do this. The resource server is still going to need to grab the access token somehow. So if the authorization server is storing them in its own database the resource server would need to make a request to the authorization server to get the token. It's a tough one.

**Comment by mdwheele** [comment]
I'll be spending some time on this. I'll pull your library into an
experimental branch and toy with some ideas. As far as public api goes, is
maintaining parity with the league package a hard requirement? I know your
api package supports both but it made me question why make a second OAUTH
server implementation if it's going to follow the same requirements. Just
curious!

There are some changes we could make under the hood, but I don't see a way
around adding methods to at least the auth server to explicitly declare the
available action of verifying a token.

I'll poke at it today and send you some experimental code.

**Comment by jasonlewis** [comment]
My initial reason for creating another package was due to some annoyances within the Leagues. Been following 4.0 and MAY look at deprecating this. What you're after is not possible in the Leagues?

**Comment by mdwheele** [comment]
Yeah, the separation I'm looking for isn't available in the League's package at the moment and I get the feeling Alex is ready to release 4.0 any day so I didn't want to drop something like this right now.  However, I know what you mean with slight annoyances.  This is pretty on-par with the 4.0.0-WIP branch, but with some subtle differences.

How about this; I'll bring it up with Alex again over email and get his opinion and move from there.  I know how much work it is to maintain a package like this, so I definitely understand possibly deprecating in favor of league's.  That'd afford you more time on the api package! :smile:

**Comment by jasonlewis** [comment]
Indeed it will!

**Comment by mdwheele** [comment]
Thanks again, Jason.  I've taken the discussion over to https://github.com/thephpleague/oauth2-server/issues/168
